### PR TITLE
charts 2.7.0

### PR DESCRIPTION
**Pull request by ConfusedVorlon**
I really like the new ability to get multiline titles...

### CODE REVIEW

**Comment by jcohenho** [comment]
+1

**Comment by elissonmichael** [comment]
It is also possible to use stack: 'group' in bar graph

**Comment by diesl** [comment]
@airblade This PR is open since half a year now. Could you please merge this or even better upgrade Chart.js to the current version? Thanks!

**Comment by airblade** [comment]
Sorry about the delay!

- Chart.js 2.7.0 is in v3.6.0 of this gem.
- Chart.js 2.7.1 is in v3.6.1 of this gem.
- Chart.js 2.7.2 is in v3.6.2 of this gem.

I haven't looked to see whether Chart.js's API has changed since 2.5.0 – it probably has, so please let me know if any of the gem's helpers need to change.

**Pull request closed without merging**
