### PR TITLE
Add argument for plugins

### PR DESCRIPTION
**Pull request by yorimitsu**
I wanted to pass the plugins to the chart helper method, but there was no argument.
So I add argument for plugins.

### CODE REVIEW

**Comment by airblade** [comment]
What are plugins?

**Comment by yorimitsu** [comment]
The plugins are functions for customizing graphs.
Please refer to the following link.
https://www.chartjs.org/docs/latest/developers/plugins.html

**Comment by airblade** [comment]
Thanks.  I released this as v3.6.4.

**Comment by yorimitsu** [comment]
I appreciate your accommodating my request so quickly. 
Thank you very much!

**Pull request merged**
